## === WORKSTATION ===

[workstation]
network = "home"
tailscale = "100.79.154.16"
keys = [
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBqVrQHdMGPKud9TYS3EtqTXLpalTD2+9M+7LfFl6Bv4 root@workstation",
  "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj009h5RovaCwxxpHfzKWCFBropvJIOKmHjs3EhrEWyFzzQb0TpKYgsrEV8P+x7xQRGpV/Lf1Qgdl5pwbj1LVs2YS2HbktYLp/MP6D/2o7qH+HcRUKag3aTHgvfStGHRCb+RP7aVUtnnnrY9pDfiLpRluCI9X6rksIlomjAP0PSEkTxVp9HL2IccEsyxxt/foNlogJ+P1MIBD+Ae92CN5YGg+BrahMOZiGCrBVSipKE6KlFUhLY4ZEODm0Sr4c18IhemDkKoqRywoBXIOHcJdnbbLFAi3xTxOZuru1XbOwoOKNMLHDkwGPdfrCACni4AtDN4FblFxHO9b6R9GW4aZgRDWIwR0nEw8IL1rv9gqiBiZ3L2A8kXUChRv4PexvT8Z7nLNksZ4hIJWmfWhpnRqCCtBRECVL2Pg0WTDUcJTjwnoNrB893uzlAnpgR1PR+LbW6RvPkN3Qkot6bQ18KugsWx6+Tpa5+vfrWZ8Fan4xHfq2FdKW6KAI3YkF3vf47d0= root@workstation",
]
age = "age1s0ckz3rka4zuutd00cn4px4yrkrq992cpejtvljsdvn5u25pkylqkfsrd0"

[workstation.ipv4]
address = "192.168.0.165"

[workstation.users.cfeeley]
keys = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHCVmAx+FNqurkG9eQ7icgqS1tOzy1JyL+spWMr477mU cfeeley@cfeeley-workstation"]
age = "age1up0p4xs0lze04acxrlxqj374ymu0dfkmc6adz2psmlz8g57ddv2qvf6pd4"


## === MACBOOK-PRO ===

[MacBook-Pro]
network = "home"
tailscale = "100.66.73.38"
keys = [
  "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBxw8UnnH5Cizu7p9r4PFGDe/azUrdC0qA3K9GtWtvf/+l4dy044X3mI+hHVigTbxDH5viYcTiH6Lk+SHl2uZuX6fkzTBaFoonEJrKeCRS25TTMmas9g7D/maDoENEF1X0acs5Ffk3CAqKlOeynGPnj4M1ovUM8wyg1lsfZXA+LVr9GLLziiZSxVBBjG341hfVP3LFijj8qIAoDnBPrlLBjrrCsHXZa1QxjjyQADC5Ty7wgqLZqhfEEmkSdUEdkEt1lW4wzJzNXM/7F+iBmLTTp2KcUTPP2kyCU8YR+QvOMafB7ufmRoMf2ERjQtCwSJCYfEot3DBOvdgL0lFBTW4T /home/cfeeley/.ssh/id_rsa",
]
# age = "age1s0ckz3rka4zuutd00cn4px4yrkrq992cpejtvljsdvn5u25pkylqkfsrd0"

[MacBook-Pro.ipv4]
address = "192.168.0.175"

[MacBook-Pro.users.cfeeley]
keys = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBu7vxj2IpJ5R4SL/TCbonZmAM6aFlruqc4z5zwBjyxo cfeeley@Connors-MacBook-Pro.local"]
# age = "age1up0p4xs0lze04acxrlxqj374ymu0dfkmc6adz2psmlz8g57ddv2qvf6pd4"

## === H8TSNER ===

[h8tsner]
network = "hetzner"
keys = [
  # "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBxw8UnnH5Cizu7p9r4PFGDe/azUrdC0qA3K9GtWtvf/+l4dy044X3mI+hHVigTbxDH5viYcTiH6Lk+SHl2uZuX6fkzTBaFoonEJrKeCRS25TTMmas9g7D/maDoENEF1X0acs5Ffk3CAqKlOeynGPnj4M1ovUM8wyg1lsfZXA+LVr9GLLziiZSxVBBjG341hfVP3LFijj8qIAoDnBPrlLBjrrCsHXZa1QxjjyQADC5Ty7wgqLZqhfEEmkSdUEdkEt1lW4wzJzNXM/7F+iBmLTTp2KcUTPP2kyCU8YR+QvOMafB7ufmRoMf2ERjQtCwSJCYfEot3DBOvdgL0lFBTW4T /home/cfeeley/.ssh/id_rsa",
]

[h8tsner.ipv4]
address = "5.161.105.71"

[h8tsner.ipv6]
address = "2a01:4ff:f0:4cff::"


[h8tsner.users.cfeeley]
keys = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBu7vxj2IpJ5R4SL/TCbonZmAM6aFlruqc4z5zwBjyxo cfeeley@Connors-MacBook-Pro.local"]

## === DEBIAN-VM ===

[debian-vm]
network = "home"
tailscale = "100.95.162.28"
keys = [ ]
# age = "age1s0ckz3rka4zuutd00cn4px4yrkrq992cpejtvljsdvn5u25pkylqkfsrd0"

[debian-vm.ipv4]
address = "192.168.0.185"

[debian-vm.users.cfeeley]
keys = [
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKPuNW9UcyAmtp9J0SJAaiMxSwqQyoJyJs9o/YcCQYMG cfeeley@debian-vm"
]

## === CFEELEY-LAPTOP ===

[cfeeley-laptop]
network = "home"
# tailscale = "100.79.154.16"
keys = [ ]
# age = "age1s0ckz3rka4zuutd00cn4px4yrkrq992cpejtvljsdvn5u25pkylqkfsrd0"

[cfeeley-laptop.ipv4]
address = "192.168.0.185"

[cfeeley-laptop.users.cfeeley]
keys = [
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL7vmjndMRRFDxn0+kMAjah/GBYb2YL9o1qncfABCu8Z connor.feeley@gmail.com",
  "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBxw8UnnH5Cizu7p9r4PFGDe/azUrdC0qA3K9GtWtvf/+l4dy044X3mI+hHVigTbxDH5viYcTiH6Lk+SHl2uZuX6fkzTBaFoonEJrKeCRS25TTMmas9g7D/maDoENEF1X0acs5Ffk3CAqKlOeynGPnj4M1ovUM8wyg1lsfZXA+LVr9GLLziiZSxVBBjG341hfVP3LFijj8qIAoDnBPrlLBjrrCsHXZa1QxjjyQADC5Ty7wgqLZqhfEEmkSdUEdkEt1lW4wzJzNXM/7F+iBmLTTp2KcUTPP2kyCU8YR+QvOMafB7ufmRoMf2ERjQtCwSJCYfEot3DBOvdgL0lFBTW4T cfeeley@cfeeley-laptop"
]
# age = "age1up0p4xs0lze04acxrlxqj374ymu0dfkmc6adz2psmlz8g57ddv2qvf6pd4"

## === INSTALLER: GRAPHICAL ===

[bootstrap-graphical]
network = "cfeeley"
